
        ACTIONX
        RBS1 30 1 /
        YEAR = 2020 MNTH = 1 DAY = 1 /
        GSATPROD
        RBS  20000 /
        /
        ENDACTIO

        ACTIONX
        RBS2 30 1 /
        YEAR = 2021 MNTH = 1 DAY = 1 /
        GSATPROD
        RBS  15000 /
        /
        ENDACTIO

        ACTIONX
        RBS3 30 1 /
        YEAR = 2022 MNTH = 1 DAY = 1 /
        GSATPROD
        RBS  10000 /
        /
        ENDACTIO

        ACTIONX
        RBS4 30 1 /
        YEAR = 2023 MNTH = 1 DAY = 1 /
        GSATPROD
        RBS  5000 /
        /
        ENDACTIO

        ACTIONX
        RBS5 30 1 /
        YEAR = 2024 MNTH = 1 DAY = 1 /
        GSATPROD
        RBS  2500 /
        /
        ENDACTIO

        ACTIONX
        RBS6 30 1 /
        YEAR = 2025 MNTH = 1 DAY = 1 /
        GSATPROD
        RBS  1000 /
        /
        ENDACTIO
